### ISSUE TITLE
Can I get some help?

### ISSUE THREAD

**Issue by Mr-Foxtrot** [JacqueSatan/NitroSniperSquad#1]
I'm having some trouble getting this to work, but I believe I am just doing something wrong.

I created a tokens.txt file in the executable directory with two tokens (main account + nitrosniper account). However whenever I run the nitrosniper executable it immediately closes the CMD window once it opens...

I noticed the usage mentioned copying openSSL binaries but I don't know where I would find that and what to do with it. Is that the issue?

**Comment by JacqueSatan** [comment]
The OpenSSL binaries are included in the release.
Could you provide more informations on the error please ? To do so, run NitroSniper.exe from the terminal.
