### ISSUE TITLE
Strip Illegal Characters

### ISSUE THREAD

**Issue by Brenex** [JacqueSatan/NitroSniperSquad#3]
Can you add the ability of the script to strip symbols to pick up obfuscated drops? e.g.

https://discord.gift/RQ&QEgS&5Z&H&eHdF&jCs - Remove the &'s

**Comment by JacqueSatan** [comment]
Sure, I didn't know these exist, thank you for the information.

**Comment by Brenex** [comment]
you misunderstand, all non alphanumeric characters should be stripped (e.g. !,@,% etc.)

**Comment by JacqueSatan** [comment]
oh sry, can u provide a list of these chars pls ?

**Comment by Brenex** [comment]
it's all the character that are not a letter or a number

**Comment by JacqueSatan** [comment]
done [commit](https://github.com/JacqueSatan/NitroSniperSquad/commit/2df9073a0154ad9bac59c390af0c7cfda646a189)
