### ISSUE TITLE
Crashes and alot of Discord disconnections also a way to detect fake code

### ISSUE THREAD

**Issue by Jev1337** [JacqueSatan/NitroSniperSquad#5]
I've been using this sniper for awhile now, I leave it running in the background of an RDP, no CPU usage or RAM; I noticed that the program crashes within 24 hours and every hour it disconnects from token and reconnects which fills up the console window alot with errors...

and btw heres a way to detect a fake code, this is just an example, there may be more ways to know

```
int temp = code().size;
if temp < 16
qDebug << "Fake Code Detected";
```

**Comment by malekamir** [comment]
also 
```
if temp > 24
qDebug << "Fake Code Detected";
```

**Comment by JacqueSatan** [comment]
It's normal for the tokens to disconnect and reconnect, it's like a "feature" I guess. But that doesn't affect the gift detection, as they reconnect at the same point they disconnect.

Also, could you provide more information on these crashes ?

**Comment by JacqueSatan** [comment]
also size verification has been added [commit](https://github.com/JacqueSatan/NitroSniperSquad/commit/d5878a69c647c559c1019136f19c2c2d9db75a1e)

**Comment by Jev1337** [comment]
I have no idea, I ran it on an RDP then later when I come back I find it closed ^^

**Comment by Jev1337** [comment]
I also want to say that code length can be 26, I didn't know until now, but I've seen a code today that is 26 long, So It's recommended to change it to 26
`code.size() > 26`

**Comment by JacqueSatan** [comment]
> I have no idea, I ran it on an RDP then later when I come back I find it closed ^^
Mh, I can't try to fix it then

Thanks for that too
